### ISSUE TITLE
three options for each kind of token

### ISSUE THREAD

**Issue by maia** [diasks2/pragmatic_tokenizer#10]
Create three options per kind of token: `:remove` (will completely remove it), `:keep_and_clean` (will only keep letters, numbers, hyphen and underscores, but not other characters like #, @, +, *, as prefix/suffix) and `:keep_original` (don't alter the token at all). The options could look like:
````ruby
options = {
    emojis:              :remove,
    stop_words:          :remove,
    urls:                :remove,
    hashtags:            :keep_and_clean,
    mentions:            :keep_and_clean,
    email_addresses:     :keep_original,
    domains:             :keep_original,
    …
    expand_contractions: true,
    language:            :en,
    punctuation:         :none,
    downcase:            true,
    minimum_length:      3,
    long_word_split:     10
}
````
E.g. when using `:keep_and_clean`, the string `"@john_doe2_"`that is identified as `:mention` would be converted to `"john_doe2"`.

**Comment by diasks2** [comment]
For stop words we probably want one more option to additionally remove English stop words (in addition to removing the stop words of the language the string is in). This is for the case where a string in a language other than English has some English mixed in.

**Comment by diasks2** [comment]
Or maybe you can select the languages you want to remove stop words:

```ruby
options = {
    stop_words: [:en, :de]
}
```

**Comment by maia** [comment]
I like the latter as there might be cases where a document mixes Spanish and Italian. Also, why stop at the stop words, what about e.g. the abbreviations and contractions?

**Comment by diasks2** [comment]
Yes, good idea.

**Comment by diasks2** [comment]
OK, this is implemented now. IMO the 3 options are only relevant for mentions and hashtags. The others are boolean options (remove or keep). For example URLS - I don't think a `keep_and_clean` option is necessary.
