### ISSUE TITLE
split long words

### ISSUE THREAD

**Issue by maia** [diasks2/pragmatic_tokenizer#11]
Add an option to split long words once they surpass a user specified length at any hyphen or underscore. This can help with languages that like to join words with a hyphen, e.g. this pseudo-translation of a German sentence: 

*"Some main-categories of the mathematics-test have sub-examples that most 14-year olds can't answer, therefor the implementation-instruction made in the 1990-years needs to be revised"*.

This would also help with pseudo-hashtags which aren't valid twitter hashtags (no hyphen allowed), e.g. #something-else.

I suggest to default `long_word_split ` at ~10 characters.

**Comment by diasks2** [comment]
I added this option: https://github.com/diasks2/pragmatic_tokenizer/blob/master/lib/pragmatic_tokenizer/tokenizer.rb#L80

NB: The default is set to *not* split at long words as I think that would be unexpected behavior. The user needs to explicitly set this option.
