### ISSUE TITLE
option :clean removes hashtags

### ISSUE THREAD

**Issue by maia** [diasks2/pragmatic_tokenizer#12]
When using clean: true it will unfortunately remove any #hashtag completely:

````ruby
> text = "cnn.com mentions this *funny* #hashtag used by @obama http://cnn.com/something"
> PragmaticTokenizer::Tokenizer.new(text, punctuation: 'none', clean: true).tokenize
=> ["cnn.com", "mentions", "this", "funny", "used", "by", "obama", "http://cnn.com/something"]
````

This is a problem as the option `:clean` is quite relevant when processing pseudo-markdown, like \*really important\* information that we want to \_emphasize\_, when using `clean: false` it will keep the symbol prefixes and suffixes.

**Comment by diasks2** [comment]
Thanks! This should be fixed now: https://github.com/diasks2/pragmatic_tokenizer/blob/master/spec/languages/english_spec.rb#L384-L390
