### ISSUE TITLE
remove_numbers should keep tokens that contain letters

### ISSUE THREAD

**Issue by maia** [diasks2/pragmatic_tokenizer#13]
I believe the option `:remove_numbers` should only remove tokens that do not contain any letter. Or allow this as option: `remove_numbers: :semi` (analogue to `:punctuation`), then the below would not return an empty array.
````ruby
> text = "2pac U2 50cent blink-182 zero7 M83 B-52s"
> PragmaticTokenizer::Tokenizer.new(text, remove_numbers: true).tokenize
=> []
````

**Comment by diasks2** [comment]
Thanks! This is available in the new version: https://github.com/diasks2/pragmatic_tokenizer/blob/master/spec/languages/english_spec.rb#L473-L504
