### ISSUE TITLE
classic_filter and non-acronyms

### ISSUE THREAD

**Issue by maia** [diasks2/pragmatic_tokenizer#15]
Due to the religiosity of central europe, many city names have a prefix that can be translated to "saint". E.g. `"St.Veit"`, which usually would be written `"St. Veit"`, but, well, that's the Internet.

When using `classic_filter: true` this string currently returns `"stveit"`. There could be many other edge cases (e.g. `"B.Obama"` is converted to `"bobama"`, `"CNN.com"` to `"cnncom"`). 

Shouldn't `classic_filter` only strip dots from acronyms if there's a maximum of ONE letter before *and* after it?

**Comment by diasks2** [comment]
Thanks! This should be fixed in the most recent version.
