### ISSUE TITLE
additional specs

### ISSUE THREAD

**Issue by maia** [diasks2/pragmatic_tokenizer#17]
Here are 14 additional specs that currently do not pass. Please let me know which of these should be moved into separate issues (for further discussion, taking care of them at a later point,…). Thanks!
````ruby
#1
it 'cleans words with symbols' do
  text = "something.com:article title !!wow look!!1"
  pt = PragmaticTokenizer::Tokenizer.new(text, clean: true)
  expect(pt.tokenize).to eq(
    ["something.com", "article", "title", "wow", "look"]
  )
end

#2
it 'knows what isnt an email address' do
  text = "the great cook.@someone something else@whoever"
  pt = PragmaticTokenizer::Tokenizer.new(text, remove_emails: true)
  expect(pt.tokenize).to eq(
    ["the", "great", "cook.@someone", "something", "else@whoever"]
  )
end

#3
# this could be tricky. maybe pass the option remove_domains a whitelisting array of tld's like: [".com", ".net", ".org", ".co.uk"] and only convert these?
# how does pragmatic_segmenter differenciate betweed the end of a sentence and a domain?
it 'knows what isnt a domain 1' do
  text = "this is a sentence.and no domain."
  pt = PragmaticTokenizer::Tokenizer.new(text, remove_domains: true)
  expect(pt.tokenize).to eq(
    ["this", "is", "a", "sentence", ".", "and", "no", "domain", "."]
  )
end

#4
# even without knowing which TLDs exist, this can never be a valid url as (I believe) no domain may only consist of a single letter
it 'knows what isnt a domain 2' do
  text = "former president g.w.bush was..."
  pt = PragmaticTokenizer::Tokenizer.new(text, remove_domains: true)
  expect(pt.tokenize).to eq(
    ["former", "president", "g.w.bush", "was", "..."]
  )
end

#5
it 'knows what isnt a domain 3' do
  text = "2.something-times"
  pt = PragmaticTokenizer::Tokenizer.new(text, remove_domains: true)
  expect(pt.tokenize).to eq(
    ["2.something-times"]
  )
end

#6
it 'identifies hashtags with numbers too' do
  text = "this is a sentence.#yay this too.#withnumbers123"
  pt = PragmaticTokenizer::Tokenizer.new(text)
  expect(pt.tokenize).to eq(
    ["this", "is", "a", "sentence", ".", "#yay", "this", "too", ".", "#withnumbers123"]
  )
end

#7
# alternatively it could split at the ampersand, but at least return something
it 'deals with html escaped entities when cleaning' do
  text = "you&amp;me"
  pt = PragmaticTokenizer::Tokenizer.new(text, clean: true)
  expect(pt.tokenize).to eq(
    ["you&me"]
  )
end

#8
# in my understanding :semi should only keep tokens including at least one letter, but when keeping the current logic a similar behavior could be implemented using minimum_length:
it 'requires presence of at least minimum_length letters per token' do
  text = "conference schedule:14.2. day one 12-01-16 26.12.2015 24°C 355€."
  pt = PragmaticTokenizer::Tokenizer.new(text, numbers: :semi, minimum_length: 4)
  expect(pt.tokenize).to eq(
    ["conference", "schedule"]
  )
end

#9
it 'splits at a comma' do
  text = "16.1. day one,17.2. day two"
  pt = PragmaticTokenizer::Tokenizer.new(text)
  expect(pt.tokenize).to eq(
    ["16.1", ".", "day", "one", ",", "17.2", ".", "day", "two"]
  )
end

#10
it 'splits at hashtags' do
  text = "some sentence#RT ... i like u2.#bono"
  pt = PragmaticTokenizer::Tokenizer.new(text, punctuation: :none)
  expect(pt.tokenize).to eq(
    ["some", "sentence", "#rt", "i", "like", "u2", "#bono"]
  )
end

#11
it 'optimizes the classic filter' do
  text = "there ́s something"
  pt = PragmaticTokenizer::Tokenizer.new(text, classic_filter: true)
  expect(pt.tokenize).to eq(
    ["there", "something"]
  )
end

#12
it 'splits emojis' do
  text = "🤔🙄"
  pt = PragmaticTokenizer::Tokenizer.new(text, classic_filter: true)
  expect(pt.tokenize).to eq(
    ["🤔", "🙄"]
  )
end

#13
# alternatively :clean=>true should clean the ':' and not return ':the'
it 'identifies prefixed symbols' do
  text = "look:the sky is blue"
  pt = PragmaticTokenizer::Tokenizer.new(text)
  expect(pt.tokenize).to eq(
    ["look", ":", "the", "sky", "is", "blue"]
  )
end

#14
it 'identifies single quotes' do
  text = "Sean Penn Sat for Secret Interview With ‘El Chapo,’ Mexican Drug"
  pt = PragmaticTokenizer::Tokenizer.new(text)
  expect(pt.tokenize).to eq(
    ["sean", "penn", "sat", "for", "secret", "interview", "with", "‘", "el", "chapo", ",", "’", "mexican", "drug"]
  )
end

````

**Comment by diasks2** [comment]
Awesome, thanks! I'll work on these today.

**Comment by diasks2** [comment]
Can you clarify examples 11 and 12:

For 11 when I copy that spec into a text editor there is a space between `there` and the apostrophe. Is this correct?

For 12, github is just showing an unknown character and when I search it on Google I get `thinking face (U+1F914)` but it does not display on my computer. Is this one of the 1012 single-character Unicode Emoji: https://github.com/franklsf95/ruby-emoji-regex ?

**Comment by diasks2** [comment]
I opened a separate issue for 7 https://github.com/diasks2/pragmatic_tokenizer/issues/18

**Comment by diasks2** [comment]
For 3, you mentioned in the past you thought it would be a bad idea to whitelist TLDs, but I think that is probably the best solution if you want it to be that precise: http://data.iana.org/TLD/tlds-alpha-by-domain.txt

**Comment by diasks2** [comment]
Apart from 11 and 12 (awaiting clarification) and the ones I moved to separate issues the above should now be passing: https://github.com/diasks2/pragmatic_tokenizer/commit/2414f56fa166112a4483727e903a03727f728c94

**Comment by maia** [comment]
As for 11, I believe it's the same character problem as with the amandapalmer example. Here's how to get the string:
````ruby
unpacked = [116, 104, 101, 114, 101, 32, 769, 115, 32, 115, 111, 109, 101, 116, 104, 105, 110, 103]
unpacked.pack("U*")
````
this should return the word "there" followed by an apostrophe, then the letter "s", a space and the word "something".

As for 12, these are emojis, and yes it seems to be `thinking face (U+1F914)`followed by `face with rolling eyes (U+ 1F644)`. They are also listed here: http://unicode.org/emoji/charts/emoji-released.html
````ruby
> text = "🤔🙄"
=> "\u{1F914}\u{1F644}"
> text.unpack("U*")
=> [129300, 128580]
````
I'll comment on the rest in a few hours.

**Comment by diasks2** [comment]
Thanks, I updated with passing specs for 11 and 12, but if you have a chance please double check and make sure it matches what you intended: https://github.com/diasks2/pragmatic_tokenizer/commit/358fe4c5b4118b24c6a76d42005cd399d6768b86

**Comment by maia** [comment]
I'll have to test them later, but judging by how githob displays the commit I doubt it, as in the code the apostroph merged with another letter. It likes to do that, it seems to be an accent that will only remain unmerged in rare cases (e.g. if the next char initially is a space). I guess one should use unpacked strings for testing here.

**Comment by maia** [comment]
As for the apostrophe, `#unpack("U*")` will return `[769]` but `[769].pack("U*").first.bytes` converts this to `[204, 129]`. Using the option `classic_filter: true` properly identifies this as apostrophe and when followed by the letter `s` will remove it. Interestingly `pack` followed by `unpack` won't work: `[769].pack("U*").first.bytes.pack("U*") => "Ì\u0081"`, which might be the cause of the apostrophe "merging" with subsequent letters to weird chars when copy&pasting it into github. I suggest to ensure that the code contains the proper bytes, therefor to use the following test instead:

````
it 'optimizes the classic filter' do
  text = [116, 104, 101, 114, 101, 32, 769, 115, 32, 115, 111, 109, 101, 116, 104, 105, 110, 103].pack("U*")
  pt = PragmaticTokenizer::Tokenizer.new(text, classic_filter: true)
  expect(pt.tokenize).to eq(
    ["there", "something"]
  )
end
````
Are there any other occurrences of apostrophes in the code where this rare version should be added? It could be relevant outside the `classic_filter` too.

**Comment by diasks2** [comment]
That specific apostrophe `\u{0301}` should now be handled (https://github.com/diasks2/pragmatic_tokenizer/commit/28d216dcd4d61b9f8f8f8ad8601d2e4fee09721a) but please reopen this issue (or a separate one) if you experience further problems.
