### ISSUE TITLE
Definition of clean

### ISSUE THREAD

**Issue by diasks2** [diasks2/pragmatic_tokenizer#18]
```ruby
it 'does not remove tokens with ampersands' do
  text = "you&amp;me"
  pt = PragmaticTokenizer::Tokenizer.new(text,
    clean: true
  )
  expect(pt.tokenize).to eq(["you&me"])
end
```

Currently clean will remove any tokens with an ampersand. Should instead the behavior be to split at `&` or to do nothing at `&` (this might also apply to the normal behavior or pragmatic_tokenizer without the clean option).

**Comment by maia** [comment]
I'd assume that the more desired option is to split than to do nothing, but that could be also be defined by `long_word_split`, meaning that this option does not only check for hyphens but also other characters. In the above spec a value of 6 or below would then lead to splitting `you&me`, and higher values would keep this as a single token?

**Comment by diasks2** [comment]
OK, I decided to split at an ampersand: https://github.com/diasks2/pragmatic_tokenizer/commit/4958c58029284e4800cb8b6af961e84fbe1e254e
