### ISSUE TITLE
options should (also) allow symbols

### ISSUE THREAD

**Issue by maia** [diasks2/pragmatic_tokenizer#2]
I do think the values of the options hash should allow symbols (or: switch all strings to symbols).

This then would be valid:
````
PragmaticTokenizer::Tokenizer.new(text, punctuation: :none).tokenize
````

**Comment by diasks2** [comment]
Good idea, this should be fixed now: https://github.com/diasks2/pragmatic_tokenizer/commit/ee21fcacce5071c6c4cacbc7f9fe5e76b39a04d9
