### ISSUE TITLE
Identifying emojis by unicode ranges?

### ISSUE THREAD

**Issue by maia** [diasks2/pragmatic_tokenizer#20]
There currently is a EMOJI_REGEX (plus a PREFIX_ and POSTFIX_ regex) that contains a list of emojis. As new emojis are introduced frequently (which will increase the maintenance work of this gem): is there a way to regex specific ranges of codepoints (or surrogate pairs), instead of searching for each emoji? A initial search brought up:

http://crocodillon.com/blog/parsing-emoji-unicode-in-javascript
https://github.com/gmac/gemoji-parser
https://github.com/mathiasbynens/emoji-regex

**Comment by diasks2** [comment]
Yes, I think we definitely need a better solution for handling emoji. I'll check into those...

**Comment by maia** [comment]
#24 might be helpful, as it might be possible to identify beginning and ending of ranges. And if not, it's at least a good list of emojis to feed to the regex.

**Comment by maia** [comment]
@diasks2 I just found an interesting gem regarding emoji regex: https://github.com/janlelis/unicode-emoji

**Comment by maia** [comment]
With 3.0.7 upwards a large unicode range is used to capture emoji (and other characters): `/[\u203C-\u3299\u{1F000}-\u{1F644}]/`. Unless this range is too large and has side effects, this issue can be closed.
