### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by diasks2** [diasks2/pragmatic_tokenizer#27]
Investigate ways to make the gem faster using stackprof. Performance has significantly fallen off as more features and checks have been added: https://github.com/diasks2/pragmatic_tokenizer/blob/master/spec/performance_spec.rb#L28-L46

**Comment by maia** [comment]
One option: reusing strings and arrays wherever possible should reduce GC and add speed. E.g. there are quite a lot of calls to `.map` which each create a new array and GC the old one, that could probably be replaced by `.map!`.

**Comment by maia** [comment]
With the most recent commits in master I'm seeing twice the speed. I'll close the issue for now, but will keep looking for further optimizations.

**Comment by diasks2** [comment]
Thanks so much! Huge improvement, I really appreciate your hard work to make it faster and more memory efficient. :+1:
