### ISSUE TITLE
long_word_split should not split emails, urls, twitter handles

### ISSUE THREAD

**Issue by maia** [diasks2/pragmatic_tokenizer#32]
The option `long_word_split` should not split twitter handles (mentions), see this undesired behavior:
````ruby
> PragmaticTokenizer::Tokenizer.new(long_word_split: 5).tokenize("@john_doe")
=> ["@john", "doe"]
> PragmaticTokenizer::Tokenizer.new(long_word_split: 5).tokenize("john_doe@something.com")
=> ["john", "doe@something.com"]
> PragmaticTokenizer::Tokenizer.new(long_word_split: 5).tokenize("http://test.com/some_path")
=> ["http://test.com/some", "path"]
````
The method `PragmaticTokenizer::Tokenizer#split_long_words!` will need to determine if a word should be preserved, and only split if it's safe to do so.

**Comment by diasks2** [comment]
I think this should take care (https://github.com/diasks2/pragmatic_tokenizer/commit/38da52d79913efd47f7fc018e8d23da1c93dddd0) of it without a huge performance hit, but if you find any additional failing strings or if you have a better way please let me know.
