### ISSUE TITLE
ActiveSupport::Multibyte::Chars causing NoMethodError

### ISSUE THREAD

**Issue by maia** [diasks2/pragmatic_tokenizer#6]
When the input string is of the class `ActiveSupport::Multibyte::Chars` (*"Chars enables you to work transparently with UTF-8 encoding in the Ruby String class without having extensive knowledge about the encoding. A Chars object accepts a string upon initialization and proxies String methods in an encoding safe manner. All the normal String methods are also implemented on the proxy."*) and contains punctuation, various NoMethodError are raised:

````
> PragmaticTokenizer::Tokenizer.new("hello world.".mb_chars).tokenize
NoMethodError: undefined method `scan' for nil:NilClass
      from /.../gems/pragmatic_tokenizer-1e862d84cfd8/lib/pragmatic_tokenizer/processor.rb:152:in `block in separate_other_ending_punc'
      from /.../gems/pragmatic_tokenizer-1e862d84cfd8/lib/pragmatic_tokenizer/processor.rb:151:in `each'
      from /.../gems/pragmatic_tokenizer-1e862d84cfd8/lib/pragmatic_tokenizer/processor.rb:151:in `separate_other_ending_punc'

> PragmaticTokenizer::Tokenizer.new("hello world. or not?".mb_chars).tokenize
NoMethodError: undefined method `downcase' for nil:NilClass
      from /.../gems/pragmatic_tokenizer-1e862d84cfd8/lib/pragmatic_tokenizer/processor.rb:130:in `block in separate_full_stop'
      from /.../gems/pragmatic_tokenizer-1e862d84cfd8/lib/pragmatic_tokenizer/processor.rb:127:in `each'
      from /.../gems/pragmatic_tokenizer-1e862d84cfd8/lib/pragmatic_tokenizer/processor.rb:127:in `each_with_index'
      from /.../gems/pragmatic_tokenizer-1e862d84cfd8/lib/pragmatic_tokenizer/processor.rb:127:in `separate_full_stop'
````
Ideally one would not be forced to run #to_s on a multibyte string before letting pragmatic_tokenizer process it.

**Comment by diasks2** [comment]
Thanks! OK, this should be taken care of now: https://github.com/diasks2/pragmatic_tokenizer/blob/master/lib/pragmatic_tokenizer/tokenizer.rb#L28

**Comment by maia** [comment]
@diasks2 Shouldn't it be possible to process multibyte strings? I'm unsure if the conversion `#to_s` has negative side effects in some languages (and also it increases the objects that need to be gc'd).

**Comment by diasks2** [comment]
Not sure. Isn't the definition of a multibyte string particular to using the `ActiveSupport` gem though?

**Comment by maia** [comment]
Yes, but as I believe a high percentage of all ruby-devs are using rails, it might be good to not convert the input. I'm not an expert regarding encodings, but Yehuda Katz [wrote](http://yehudakatz.com/2010/05/05/ruby-1-9-encodings-a-primer-and-the-solution-for-rails/) an article about encodings and Rails:

*"Finally, Rails itself provides a pure-Ruby UTF-8 library that mops up a lot of the remaining issues. Specifically, it provides an alternate String class that can properly handle operations like split, truncate, index, justify and other operations that need to operate on characters, not bytes. It then uses this library internally in helpers like truncate, transparently avoiding a whole other class of issue."*

It seems like converting the input to a string could cause problems with UTF-16 and UTF-32 text? Katz also mentioned that e.g. SHIFT-JIS cannot be losslessly encoded to UTF-8, which I believe would happen on `#to_s`. Anyways, I'm unsure, but I'd be careful with using `#to_s` as if someone uses a multibyte chars object as input there might be a good reason to do so.

**Comment by diasks2** [comment]
Good point. In that case I think we should raise an error if the input text is not a string (https://github.com/diasks2/pragmatic_tokenizer/commit/2e7c1ffeb51a52a7ed3c4ebef2bdbe8174106d3d). I don't think it makes sense to have ActiveSupport as a dependency and I can't say I understand enough about what `ActiveSupport::Multibyte::Chars` is doing to be able to ensure we are handling edge cases.
